/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buildyourevent;


import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ComboBoxModel;
import java.awt.event.*;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author ASUS
 */
public class BYE_CUSTOM extends javax.swing.JFrame {
    int jumlah;

    /**
     * Creates new form BYE_OTHER
     */
    public BYE_CUSTOM() {
        initComponents();
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
                addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e)
                {
                    JOptionPane.showMessageDialog(null,"Thank You");
                }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        cbstage = new javax.swing.JComboBox();
        cbcuttery = new javax.swing.JComboBox();
        cblighting = new javax.swing.JComboBox();
        cbsound = new javax.swing.JComboBox();
        cbinstrument = new javax.swing.JComboBox();
        tfstand = new javax.swing.JTextField();
        tftable = new javax.swing.JTextField();
        tfgenset = new javax.swing.JTextField();
        tfchair = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfprice = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbstand = new javax.swing.JCheckBox();
        cbtable = new javax.swing.JCheckBox();
        cbchair = new javax.swing.JCheckBox();
        cbgenset = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnprint = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        tfhargagenset = new javax.swing.JTextField();
        tfhargainstrument = new javax.swing.JTextField();
        tfhargasound = new javax.swing.JTextField();
        tfhargalighting = new javax.swing.JTextField();
        tfhargacuttery = new javax.swing.JTextField();
        tfhargachair = new javax.swing.JTextField();
        tfhargatable = new javax.swing.JTextField();
        tfhargastand = new javax.swing.JTextField();
        tfhargastage = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bye_music_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfbayar = new javax.swing.JTextArea();
        tfkembalian = new javax.swing.JTextField();
        cekkembalian = new javax.swing.JButton();
        rupiah = new javax.swing.JLabel();
        rupiah1 = new javax.swing.JLabel();
        rupiah2 = new javax.swing.JLabel();
        rupiah3 = new javax.swing.JLabel();
        rupiah4 = new javax.swing.JLabel();
        rupiah5 = new javax.swing.JLabel();
        rupiah6 = new javax.swing.JLabel();
        rupiah7 = new javax.swing.JLabel();
        rupiah8 = new javax.swing.JLabel();
        rupiah9 = new javax.swing.JLabel();
        rupiah10 = new javax.swing.JLabel();
        rupiah11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cbstage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. SMALL (4x6 m2)", "2. MEDIUM (6x8 m2)", "3. LARGE (10x16 m2)", "4. EXTRALARGE (20x22 m2)", " " }));
        cbstage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstageActionPerformed(evt);
            }
        });

        cbcuttery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. SMALL(200pcs)", "2. MEDIUM(500pcs)", "3. LARGE(800pcs)", "4. EXTRA LARGE(1200pcs)", " " }));
        cbcuttery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcutteryActionPerformed(evt);
            }
        });

        cblighting.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. BASIC", "2. MEDIUM", "3. EXPERT", "4. EXCLUSIVE", " " }));
        cblighting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblightingActionPerformed(evt);
            }
        });

        cbsound.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. BASIC", "2. MEDIUM", "3. EXPERT", " " }));
        cbsound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsoundActionPerformed(evt);
            }
        });

        cbinstrument.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "1. BASIC", "2.MEDIUM", "3.EXPERT", " " }));
        cbinstrument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbinstrumentActionPerformed(evt);
            }
        });

        tfstand.setEditable(false);
        tfstand.setBackground(new java.awt.Color(153, 153, 153));
        tfstand.setText("0");
        tfstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfstandActionPerformed(evt);
            }
        });
        tfstand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfstandKeyReleased(evt);
            }
        });

        tftable.setEditable(false);
        tftable.setBackground(new java.awt.Color(153, 153, 153));
        tftable.setText("0");
        tftable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftableActionPerformed(evt);
            }
        });
        tftable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tftableKeyReleased(evt);
            }
        });

        tfgenset.setEditable(false);
        tfgenset.setBackground(new java.awt.Color(153, 153, 153));
        tfgenset.setText("0");
        tfgenset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfgensetActionPerformed(evt);
            }
        });
        tfgenset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfgensetKeyReleased(evt);
            }
        });

        tfchair.setEditable(false);
        tfchair.setBackground(new java.awt.Color(153, 153, 153));
        tfchair.setText("0");
        tfchair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfchairActionPerformed(evt);
            }
        });
        tfchair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfchairKeyReleased(evt);
            }
        });

        jButton2.setText("Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tfprice.setBackground(new java.awt.Color(153, 153, 153));
        tfprice.setColumns(20);
        tfprice.setRows(5);
        tfprice.setText("0");
        jScrollPane1.setViewportView(tfprice);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("X");

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("X");

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("X");

        cbstand.setForeground(new java.awt.Color(204, 204, 204));
        cbstand.setText("STAND");
        cbstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstandActionPerformed(evt);
            }
        });

        cbtable.setForeground(new java.awt.Color(204, 204, 204));
        cbtable.setText("TABLE");
        cbtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtableActionPerformed(evt);
            }
        });

        cbchair.setForeground(new java.awt.Color(204, 204, 204));
        cbchair.setText("CHAIR");
        cbchair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbchairActionPerformed(evt);
            }
        });

        cbgenset.setForeground(new java.awt.Color(204, 204, 204));
        cbgenset.setText("GENSET 700W");
        cbgenset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgensetActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("STAGE");

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("CUTTERY");

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("LIGHTING");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("SOUND");

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("INSTRUMENT");

        jButton6.setText("Info");
        jButton6.setPreferredSize(new java.awt.Dimension(45, 32));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Info");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Info");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Price :");

        tfhargagenset.setEditable(false);
        tfhargagenset.setText("0");
        tfhargagenset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargagensetActionPerformed(evt);
            }
        });

        tfhargainstrument.setEditable(false);
        tfhargainstrument.setText("0");
        tfhargainstrument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargainstrumentActionPerformed(evt);
            }
        });

        tfhargasound.setEditable(false);
        tfhargasound.setText("0");
        tfhargasound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargasoundActionPerformed(evt);
            }
        });

        tfhargalighting.setEditable(false);
        tfhargalighting.setText("0");
        tfhargalighting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargalightingActionPerformed(evt);
            }
        });

        tfhargacuttery.setEditable(false);
        tfhargacuttery.setText("0");
        tfhargacuttery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargacutteryActionPerformed(evt);
            }
        });

        tfhargachair.setEditable(false);
        tfhargachair.setText("0");
        tfhargachair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargachairActionPerformed(evt);
            }
        });

        tfhargatable.setEditable(false);
        tfhargatable.setText("0");
        tfhargatable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargatableActionPerformed(evt);
            }
        });

        tfhargastand.setEditable(false);
        tfhargastand.setText("0");
        tfhargastand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargastandActionPerformed(evt);
            }
        });

        tfhargastage.setEditable(false);
        tfhargastage.setText("0");
        tfhargastage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfhargastageActionPerformed(evt);
            }
        });

        btnhitung.setText("Total");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bye_music_label.setBackground(new java.awt.Color(255, 255, 255));
        bye_music_label.setFont(new java.awt.Font("GeoSlab703 MdCn BT", 1, 48)); // NOI18N
        bye_music_label.setForeground(new java.awt.Color(255, 255, 255));
        bye_music_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bye_music_label.setText("Build Your Event");
        bye_music_label.setToolTipText("");
        jPanel2.add(bye_music_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 383, 79));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("CaptainMarvel", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CHOOSE WHAT YOU NEED");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 16));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2150, 6, -1, 79));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 6, -1, 79));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tfbayar.setBackground(new java.awt.Color(153, 153, 153));
        tfbayar.setColumns(20);
        tfbayar.setRows(5);
        tfbayar.setText("0");
        tfbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfbayarKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tfbayar);

        tfkembalian.setEditable(false);
        tfkembalian.setBackground(new java.awt.Color(153, 153, 153));
        tfkembalian.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tfkembalian.setText("0");
        tfkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkembalianActionPerformed(evt);
            }
        });
        tfkembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfkembalianKeyReleased(evt);
            }
        });

        cekkembalian.setText("Check");
        cekkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekkembalianActionPerformed(evt);
            }
        });

        rupiah.setForeground(new java.awt.Color(204, 204, 204));
        rupiah.setText("Rp.");

        rupiah1.setForeground(new java.awt.Color(204, 204, 204));
        rupiah1.setText("Rp.");

        rupiah2.setForeground(new java.awt.Color(204, 204, 204));
        rupiah2.setText("Rp.");

        rupiah3.setForeground(new java.awt.Color(204, 204, 204));
        rupiah3.setText("Rp.");

        rupiah4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rupiah4.setForeground(new java.awt.Color(204, 204, 204));
        rupiah4.setText("Rp.");

        rupiah5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rupiah5.setForeground(new java.awt.Color(204, 204, 204));
        rupiah5.setText("Rp.");

        rupiah6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rupiah6.setForeground(new java.awt.Color(204, 204, 204));
        rupiah6.setText("Rp.");

        rupiah7.setForeground(new java.awt.Color(204, 204, 204));
        rupiah7.setText("Rp.");

        rupiah8.setForeground(new java.awt.Color(204, 204, 204));
        rupiah8.setText("Rp.");

        rupiah9.setForeground(new java.awt.Color(204, 204, 204));
        rupiah9.setText("Rp.");

        rupiah10.setForeground(new java.awt.Color(204, 204, 204));
        rupiah10.setText("Rp.");

        rupiah11.setForeground(new java.awt.Color(204, 204, 204));
        rupiah11.setText("Rp.");

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbstand)
                                    .addComponent(cbtable)
                                    .addComponent(cbchair)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(cbgenset))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbstage, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfstand, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tftable, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfchair, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfgenset, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cbsound, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cblighting, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbcuttery, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbinstrument, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargagenset, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargainstrument, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargastage, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargastand, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargatable, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargachair, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargalighting, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfhargasound, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rupiah9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfhargacuttery, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(rupiah4)
                                .addGap(32, 32, 32)
                                .addComponent(tfkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel1))
                                    .addComponent(rupiah6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rupiah5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cekkembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbstage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfstand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbstand))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tftable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbtable))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfchair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbchair))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfgenset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbgenset)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cblighting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rupiah)))
                            .addComponent(tfhargalighting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbsound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jButton7)
                            .addComponent(tfhargasound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbinstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jButton8)
                            .addComponent(tfhargainstrument, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah2))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cbcuttery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(tfhargacuttery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfhargastage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfhargastand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfhargatable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfhargachair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfhargagenset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah3))))
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rupiah6)
                    .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rupiah4)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cekkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbcutteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcutteryActionPerformed
        // TODO add your handling code here:
        int pilih;
        pilih = cbcuttery.getSelectedIndex();
        hargacuttery(pilih);
    }//GEN-LAST:event_cbcutteryActionPerformed
public int hargacuttery(int pilih)
{
    String ukuranCuttery;
        int hargaCuttery = 0;
    switch (pilih)
        {
            case 1:
                ukuranCuttery = String.valueOf(cbcuttery.getSelectedItem());
                hargaCuttery = 300000;
                break;
            case 2:
                ukuranCuttery = String.valueOf(cbcuttery.getSelectedItem());
                hargaCuttery = 600000;
                break;
            case 3:
                ukuranCuttery = String.valueOf(cbcuttery.getSelectedItem());
                hargaCuttery = 900000;
                break;
            case 4:
                ukuranCuttery = String.valueOf(cbcuttery.getSelectedItem());
                hargaCuttery = 1300000;
                break;
        }
        tfhargacuttery.setText("" + hargaCuttery);
        return hargaCuttery;
}
    private void cblightingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblightingActionPerformed
        // TODO add your handling code here:
        int pilih;
       
        pilih = cblighting.getSelectedIndex();
        hargalighting(pilih);
    }//GEN-LAST:event_cblightingActionPerformed

    public int hargalighting(int pilih)
    {
         String ukuranLighting;
        int hargaLighting = 0;
         switch (pilih)
        {
            case 1:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 1500000;
                break;
            case 2:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 3000000;
                break;
            case 3:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 5000000;
                break;
            case 4:
                ukuranLighting = String.valueOf(cblighting.getSelectedItem());
                hargaLighting = 7000000;
                break;
        }
        tfhargalighting.setText("" + hargaLighting);
        return hargaLighting;
    }
    
    private void cbsoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsoundActionPerformed
        // TODO add your handling code here:
        int pilih;
        
        pilih = cbsound.getSelectedIndex();
        hargasound(pilih);
    }//GEN-LAST:event_cbsoundActionPerformed

    public int hargasound(int pilih){
        String ukuranSound;
        int hargaSound = 0;
        switch (pilih)
        {
            case 1:
                ukuranSound = String.valueOf(cbsound.getSelectedItem());
                hargaSound = 600000;
                break;
            case 2:
                ukuranSound = String.valueOf(cbsound.getSelectedItem());
                hargaSound = 1500000;
                break;
            case 3:
                ukuranSound = String.valueOf(cbsound.getSelectedItem());
                hargaSound = 2000000;
                break;

        }
        tfhargasound.setText("" + hargaSound);
        return hargaSound;
    }
    private void cbinstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbinstrumentActionPerformed
        // TODO add your handling code here:
        int pilih;
        pilih = cbinstrument.getSelectedIndex();
        hargainstrument(pilih);
    }//GEN-LAST:event_cbinstrumentActionPerformed

    public int hargainstrument(int pilih)
    {
        
        String ukuranInstrument;
        int hargaInstrument = 0;
        switch (pilih)
        {
            case 1:
                ukuranInstrument = String.valueOf(cbinstrument.getSelectedItem());
                hargaInstrument = 500000;
                break;
            case 2:
                ukuranInstrument = String.valueOf(cbinstrument.getSelectedItem());
                hargaInstrument = 1200000;
                break;
            case 3:
                ukuranInstrument = String.valueOf(cbinstrument.getSelectedItem());
                hargaInstrument = 2300000;
                break;
        }
        tfhargainstrument.setText("" + hargaInstrument);
        return hargaInstrument;
    }
    
    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
int h1,h2,h3,h4,h5,h6,h7,h8,h9,z1,z2,z3,z4,z5,z6,z7,z8;
h1 = Integer.valueOf(tfhargastage.getText());
h2 = Integer.valueOf(tfhargacuttery.getText());
h3 = Integer.valueOf(tfhargalighting.getText());
h4 = Integer.valueOf (tfhargasound.getText());
h5 = Integer.valueOf (tfhargainstrument.getText());
z1 = Integer.valueOf(tfstand.getText());
z2 = Integer.valueOf(tfhargastand.getText());
z3 = Integer.valueOf(tftable.getText());
z4 = Integer.valueOf(tfhargatable.getText());
z5 = Integer.valueOf(tfchair.getText());
z6 = Integer.valueOf(tfhargachair.getText());
z7 = Integer.valueOf(tfgenset.getText());
z8 = Integer.valueOf(tfhargagenset.getText());
h6 = perkalian(z1,z2);
h7 = perkalian(z3,z4);
h8 = perkalian(z5,z6);
h9 = perkalian(z7,z8);

jumlah = totalharga(h1, h2, h3, h4, h5, h6, h7, h8, h9);
tfprice.setText(Integer.toString(jumlah));

tfprice.setEditable(false);


    }//GEN-LAST:event_btnhitungActionPerformed
    public String hapus()
    {
    tfhargastage.setText("0");
tfhargacuttery.setText("0");
tfhargalighting.setText("0");
tfhargasound.setText("0");
tfhargainstrument.setText("0");
tfhargagenset.setText("0");
tfhargastand.setText("0");
tfhargatable.setText("0");
tfhargachair.setText("0");
tfhargagenset.setText("0");
tfprice.setText("0");
cbstage.setSelectedIndex(0);
cbcuttery.setSelectedIndex(0);
cblighting.setSelectedIndex(0);
cbsound.setSelectedIndex(0);
cbinstrument.setSelectedIndex(0);
tfstand.setText("");
tftable.setText("");
tfchair.setText("");
tftable.setText("");
cbstand.setSelected(false);
cbtable.setSelected(false);
cbchair.setSelected(false);
cbgenset.setSelected(false);
        return null;
}
    
        public int totalharga
        (int stage,int stand,int table,int chair,int cuttery,int lighting,int sound,int instrument,int genset) 
    {
               String hasil; 
                jumlah = stage+stand+table+chair+cuttery+lighting+sound+instrument+genset;
                hasil = Double.toString(jumlah);
         
                return jumlah;
    }
         public int changes (int money,int total)
        {
            int a;
            String hasil; 
            a = money-total;
            hasil = Double.toString(a);
                return a;
        }
         
          public int perkalian
        (int angka1,int angka2) 
    {
        int a;
        String hasil;
        a =  angka1*angka2;
         hasil = Double.toString(a);
                return a;
    }
        
    private void cbstageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstageActionPerformed
        // TODO add your handling code here:
        int pilih;
        pilih = cbstage.getSelectedIndex();
     hargastage(pilih);           
    }//GEN-LAST:event_cbstageActionPerformed

    private void tfhargastageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargastageActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_tfhargastageActionPerformed

    public int hargastage(int pilih)
    {
        String ukuranTenda;
        int hargaTenda = 0;
        switch (pilih)
        {
            case 0 :
                ukuranTenda = String.valueOf (cbstage.getSelectedItem());
                hargaTenda = 0;
                break;
            case 1:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 1200000;
                break;
            case 2:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 2000000;
                break;
            case 3:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 4000000;
                break;
            case 4:
                ukuranTenda = String.valueOf(cbstage.getSelectedItem());
                hargaTenda = 7000000;
                break;
        }
        tfhargastage.setText("" + hargaTenda);
        
        return  hargaTenda;
    }   
    
    
    private void tfhargastandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargastandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargastandActionPerformed

    private void tfhargatableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargatableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargatableActionPerformed

    private void tfhargalightingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargalightingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargalightingActionPerformed

    private void tfhargainstrumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargainstrumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargainstrumentActionPerformed

    private void tfhargachairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargachairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargachairActionPerformed

    private void tfhargasoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargasoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargasoundActionPerformed

    private void tfhargacutteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargacutteryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargacutteryActionPerformed

    private void cbstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstandActionPerformed
        // TODO add your handling code here:
        int stand = 100000;
        if (cbstand.isSelected())
        {
            tfhargastand.setText("" + cbstand.getText());
            tfhargastand.setText(""+ stand);
            tfstand.setEditable(true);
             tfstand.setText("");
        }
        else
        {
            tfhargastand.setText("0");
            tfstand.setEditable(false);
            tfstand.setText("0");
        }
        tfhargastand.setEditable(false);
    }//GEN-LAST:event_cbstandActionPerformed

    private void cbtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtableActionPerformed
        // TODO add your handling code here:
        int table = 30000;
        if (cbtable.isSelected())
            
        {
            tfhargatable.setText("" + cbtable.getText());
            tfhargatable.setText(""+ table);
            tftable.setEditable(true);
            tftable.setText("");
        }
        else
        {
            tfhargatable.setText("0");
            tftable.setEditable(false);
            tftable.setText("0");
        }
        tfhargatable.setEditable(false);
    }//GEN-LAST:event_cbtableActionPerformed

    private void tftableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftableActionPerformed

    private void tfstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfstandActionPerformed

    }//GEN-LAST:event_tfstandActionPerformed

    private void cbchairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbchairActionPerformed
        // TODO add your handling code here:
        int chair = 15000;
        if (cbchair.isSelected())
        {
            tfhargachair.setText("" + cbchair.getText());
            tfhargachair.setText(""+ chair);
            tfchair.setEditable(true);
            tfchair.setText("");
        }
        else
        {
            tfhargachair.setText("0");
            tfchair.setEditable(false);
            tfchair.setText("0");
        }
        tfhargachair.setEditable(false);
                                  
    }//GEN-LAST:event_cbchairActionPerformed

    private void cbgensetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgensetActionPerformed
        // TODO add your handling code here:
        int genset = 700000;
        if (cbgenset.isSelected())
        {
            tfhargagenset.setText("" + cbgenset.getText());
            tfhargagenset.setText(""+ genset);
            tfgenset.setEditable(true);
            tfgenset.setText("");
        }
        else
        {
            tfhargagenset.setText("0");
            tfgenset.setText("0");
            tfgenset.setEditable(false);
        }
        {
        
        tfhargagenset.setEditable(false);
    }//GEN-LAST:event_cbgensetActionPerformed
    }
    private void tfhargagensetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfhargagensetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfhargagensetActionPerformed

    private void tfgensetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfgensetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfgensetActionPerformed

    private void tfchairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfchairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfchairActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed

          ComboBoxModel h = cbstage.getModel();
          ComboBoxModel i = cbcuttery.getModel();
          ComboBoxModel j = cblighting.getModel();
          ComboBoxModel k = cbsound.getModel();
          ComboBoxModel l = cbinstrument.getModel();
          String m = tfstand.getText();
          String n = tftable.getText();
          String o = tfchair.getText();
          String p = tfgenset.getText();
          String q = tfprice.getText();
        BYE_RECEIPT da = new BYE_RECEIPT();
        BYE_RECEIPT.taprintstand.setText(m);
        BYE_RECEIPT.taprinttable.setText(n);
        BYE_RECEIPT.taprintchair.setText(o);
        BYE_RECEIPT.taprintgenset.setText(p);
        BYE_RECEIPT.cbtenda.setModel(h);
        BYE_RECEIPT.cbtenda.setEnabled(false);
        BYE_RECEIPT.cbalatmakan.setModel(i);
        BYE_RECEIPT.cbalatmakan.setEnabled(false);
        BYE_RECEIPT.cbband.setModel(l);
        BYE_RECEIPT.cbband.setEnabled(false);
        BYE_RECEIPT.cbspeaker.setModel(k);
        BYE_RECEIPT.cbspeaker.setEnabled(false);
        BYE_RECEIPT.cblampu.setModel(j);
        BYE_RECEIPT.cblampu.setEnabled(false);
        BYE_RECEIPT.tfharga.setText(q);
        this.dispose();
        da.setVisible(true);   
    }//GEN-LAST:event_btnprintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "200 Sets of Cutlery\n"
                        + "\n"
    + "Middle : \n"
                        + "500 Sets of Cutlery\n"
                                + "\n"
    + "Expert : \n"
                        + "800 Sets of Cutlery\n"
                                + "\n"
    + "Exclusive : \n"
                        + "1200 Set of Cutlery\n";
  textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Cutlery",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png")); 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "- 1 Speaker, 2 Mic, 1 Soundmixer\n"
                        + "\n"
                        + "Medium : \n"
                        + "- 2 Speaker, 4 Mic, 1 Soundmixer \n"
                        + "\n"
                        + "Expert : \n"
                        + "- 4 Speaker, 6 Mic, 1 Soundmixer \n"
                        + "\n";
                textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Sound",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png"));
 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "- 1 Speaker, 2 Mic, 1 Soundmixer\n"
                        + "\n"
                        + "Medium : \n"
                        + "- 2 Speaker, 4 Mic, 1 Soundmixer \n"
                        + "\n"
                        + "Expert : \n"
                        + "- 4 Speaker, 6 Mic, 1 Soundmixer \n"
                        + "\n";
                textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Sound",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png"));

    }                                        

    private void btninstrumentActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
                JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "- 1 Keyboard, 1 Guitar\n"
                        + "\n"
                        + "Medium : \n"
                        + "- 1 Keyboard, 1 Guitar, 1 Bass, 1 Drum \n"
                        + "\n"
                        + "Expert : \n"
                        + "- 1 Keyboard, 2 Guitar, 1 Bass, 1 Drum, 1 DJ Mixer \n"
                        + "\n";
                textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Instrument",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png"));

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                JTextArea textArea = new JTextArea(30,10);
  String text = "Basic : \n"
                        + "-Par\n"
                        + "-Projector \n"
                        + "-Panel \n"
                                + "\n"
    + "Middle : \n"
                        + "-Par\n"
                        + "-Projector\n"
                        + "-Moving\n"
                        + "-Scanner\n"
                                + "\n"
    + "Expert : \n"
                        + "-Par\n"
                        + "-Projector\n"
                        + "-Moving\n"
                        + "-Pinspot\n"
                        + "-Centerpiece\n"
                                + "\n"
    + "Exclusive : \n"
                        + "-Par\n"
                        + "-Projector\n"
                        + "-Moving\n"
                        + "-Pinspot\n"
                        + "-Centerpiece\n"
                        + "-Followspot\n"
                        + "-Pixel\n"
                        + "-Decorative\n";
  textArea.setText(text);
  textArea.setEditable(false);
    
  JScrollPane scroll = new JScrollPane(textArea);
    
  JOptionPane.showMessageDialog(null,scroll,"Information Lighting",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/Gambar/MovieIcon.png")); 
  
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
hapus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tfstandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfstandKeyReleased
        hitungstand(1);
    }//GEN-LAST:event_tfstandKeyReleased

    private void tftableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tftableKeyReleased
        hitungtable(1);
    }//GEN-LAST:event_tftableKeyReleased

    private void tfchairKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfchairKeyReleased
        hitungchair(1);
    }//GEN-LAST:event_tfchairKeyReleased

    private void tfgensetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfgensetKeyReleased
        hitunggenset(1);
    }//GEN-LAST:event_tfgensetKeyReleased

    private void tfkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkembalianActionPerformed

    private void tfkembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfkembalianKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkembalianKeyReleased

    private void tfbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfbayarKeyReleased

    }//GEN-LAST:event_tfbayarKeyReleased

    private void cekkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekkembalianActionPerformed
        int c1,c2,kembalian;
        c1=Integer.valueOf(tfbayar.getText());
        c2=Integer.valueOf(tfprice.getText());
        
        kembalian = changes(c1,c2);
        tfkembalian.setText(Integer.toString(kembalian));
                
    }//GEN-LAST:event_cekkembalianActionPerformed
    
    
    private void hitungstand(int harga)
    {
        int jumlahstand = Integer.parseInt(tfstand.getText())*100000;
        tfhargastand.setText(Integer.toString(jumlahstand));
    }
    private void hitungtable(int harga)
    {
        int jumlahtable = Integer.parseInt(tftable.getText())*30000;
        tfhargatable.setText(Integer.toString(jumlahtable));
    }
    private void hitungchair(int harga)
    {
        int jumlahchair = Integer.parseInt(tfchair.getText())*15000;
        tfhargachair.setText(Integer.toString(jumlahchair));
    }
    private void hitunggenset(int harga)
    {
        int jumlahgenset = Integer.parseInt(tfstand.getText())*700000;
        tfhargagenset.setText(Integer.toString(jumlahgenset));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BYE_CUSTOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BYE_CUSTOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnhitung;
    private javax.swing.JToggleButton btnprint;
    private javax.swing.JLabel bye_music_label;
    private javax.swing.JCheckBox cbchair;
    public static javax.swing.JComboBox cbcuttery;
    private javax.swing.JCheckBox cbgenset;
    public static javax.swing.JComboBox cbinstrument;
    public static javax.swing.JComboBox cblighting;
    public static javax.swing.JComboBox cbsound;
    public static javax.swing.JComboBox cbstage;
    private javax.swing.JCheckBox cbstand;
    private javax.swing.JCheckBox cbtable;
    private javax.swing.JButton cekkembalian;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rupiah;
    private javax.swing.JLabel rupiah1;
    private javax.swing.JLabel rupiah10;
    private javax.swing.JLabel rupiah11;
    private javax.swing.JLabel rupiah2;
    private javax.swing.JLabel rupiah3;
    private javax.swing.JLabel rupiah4;
    private javax.swing.JLabel rupiah5;
    private javax.swing.JLabel rupiah6;
    private javax.swing.JLabel rupiah7;
    private javax.swing.JLabel rupiah8;
    private javax.swing.JLabel rupiah9;
    public static javax.swing.JTextArea tfbayar;
    public static javax.swing.JTextField tfchair;
    public static javax.swing.JTextField tfgenset;
    public static javax.swing.JTextField tfhargachair;
    public static javax.swing.JTextField tfhargacuttery;
    public static javax.swing.JTextField tfhargagenset;
    public static javax.swing.JTextField tfhargainstrument;
    public static javax.swing.JTextField tfhargalighting;
    public static javax.swing.JTextField tfhargasound;
    public static javax.swing.JTextField tfhargastage;
    public static javax.swing.JTextField tfhargastand;
    public static javax.swing.JTextField tfhargatable;
    public static javax.swing.JTextField tfkembalian;
    private javax.swing.JTextArea tfprice;
    public static javax.swing.JTextField tfstand;
    public static javax.swing.JTextField tftable;
    // End of variables declaration//GEN-END:variables
}
